#include <iostream>
#include <vector>

using namespace std;

int main() {
    long evens_sum {2};
    long term1 {1};
    long term2 {2};
    long next_term {0};
    while (term1 + term2 <= 4'000'000){
        next_term = term1 + term2;
        if (next_term % 2 == 0)
            evens_sum += next_term;
        term1 = term2;
        term2 = next_term;
    }
    cout << "----- Project Euler -----\n"
        << "Problem 2 - Even Fibonacci numbers\n"
        << "Each new term in the Fibonacci sequence is generated by adding\n"
        << "the previous two terms. By starting with 1 and 2, the first 10\n"
        << "terms will be: 1, 2. 3, 5, 8, 13, 21, 34, 55, 89, ...\n\n"
        << "By considering the terms in the Fibonacci sequence whose values\n"
        << "do not exceed four million, find the sum of the even-valued terms.\n"
        << "Answer: " << evens_sum
        << endl;
    
    return 0;
}